### ISSUE TITLE
Failed to build gecode library - Windows 8.1

### ISSUE THREAD

**Issue by GitTH** [chef/dep-selector-libgecode#25]
I'm trying to `gem install berkshelf` but it fails when attempting to compile Gecode.

I'm running Windows 8.1 and have just installed
- vagrant_1.6.3
- VirtualBox-4.3.12-93733-Win
- rubyinstaller-2.0.0-p481
- DevKit-mingw64-32-4.7.2-20130224-1151-sfx

The error I'm getting is:

```
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing berkshelf:
        ERROR: Failed to build gem native extension.

    P:/Ruby200/bin/ruby.exe extconf.rb
checking for the host operating system... Windows
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for diff... ok
checking for tar... no
configure: error: In order to compile Gecode, you need the tar tool.
extconf.rb:94:in `block in run': Failed to build gecode library. (GecodeBuild::B
uildError)
        from extconf.rb:93:in `chdir'
        from extconf.rb:93:in `run'
        from extconf.rb:100:in `<main>'
-> sh P:/Ruby200/lib/ruby/gems/2.0.0/gems/dep-selector-libgecode-1.0.1/ext/libge
code3/vendor/gecode-3.7.3/configure --prefix=P:/Ruby200/lib/ruby/gems/2.0.0/gems
/dep-selector-libgecode-1.0.1/lib/dep-selector-libgecode/vendored-gecode --disab
le-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm --disabl
e-doc-docset --disable-qt --disable-examples --disable-flatzinc --with-host-os=w
indows


Gem files will remain installed in P:/Ruby200/lib/ruby/gems/2.0.0/gems/dep-selec
tor-libgecode-1.0.1 for inspection.
Results logged to P:/Ruby200/lib/ruby/gems/2.0.0/gems/dep-selector-libgecode-1.0
.1/ext/libgecode3/gem_make.out`
```

Not sure if this is similar to other reported issues but I'm open to any suggestions to complete the install.

**Comment by gh2k** [comment]
For people landing here from Google (like I did) there are instructions on building on Windows directly in the README. Specifically, you need to ensure that you're using a proper tar.exe. If you have Git's tar.exe in your path, Bad Things will happen.
