### ISSUE TITLE
msysgit tar breaks during compilation

### ISSUE THREAD

**Issue by btm** [chef/dep-selector-libgecode#29]
This is a known issue with the tar that comes with git bash. Both the [chef-client MSI](http://www.getchef.com/chef/install/) and the [chefdk windows alpha builds](http://lists.opscode.com/sympa/arc/chef/2014-06/msg00244.html) have a good version of tar in them.

Related discussion: https://github.com/berkshelf/berkshelf/issues/1184#issuecomment-42244272

```
                cp ./$f/*.mzn \
                  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode/share/gecode/mznlib; done
      0 [main] tar 6364 open_stackdumpfile: Dumping stack trace to tar.exe.stackdump
      0 [main] tar 9680 open_stackdumpfile: Dumping stack trace to tar.exe.stackdump
make[1]: *** [doinstallheaders] Error 5
make[1]: Leaving directory `/usr/lib/ruby/gems/1.9.1/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3'
make: *** [installlib] Error 2
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
        from extconf.rb:97:in `chdir'
        from extconf.rb:97:in `run'
        from extconf.rb:104:in `<main>'
```

**Comment by drag00n** [comment]
@danielsdeleo I can add this. Are you referring to the 4 steps that you listed for installing on windows?

**Comment by danielsdeleo** [comment]
@drag00n yes, exactly that, my note on berkshelf#1184 that BTM referenced.

**Comment by jkeiser** [comment]
Just ran into this, glad to have the issue here. I have to wonder if it's worth putting in a message in our own compile stuff if we detect you are using the git tar.exe.
