### ISSUE TITLE
unable to do bundle install in CentOS (Failed to build gecode library. (GecodeBuild::BuildError))

### ISSUE THREAD

**Issue by shortdudey123** [chef/dep-selector-libgecode#44]
I am unable to install the dep-selector-libgecode gem with bundle install on a CentOS 7.1 host w/ 15 gig ram.  Not sure what i am doing wrong.

```
Installing dep-selector-libgecode 1.0.2 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
-> sh /home/XXXXX/.bundle/ruby/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3/configure --prefix=/home/XXXXX/.bundle/ruby/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode --disable-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm --disable-doc-docset --disable-qt --disable-examples --disable-flatzinc
checking for the host operating system... Linux
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether the C++ compiler works... no
configure: error: in `/home/XXXX/.bundle/ruby/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
	from extconf.rb:97:in `chdir'
	from extconf.rb:97:in `run'
	from extconf.rb:104:in `<main>'
```

**Comment by rmoriz** [comment]
`checking whether the C++ compiler works... no`

try `yum install gcc-c++` or `yum install gcc-c++.x86_64`

**Comment by shortdudey123** [comment]
Thanks!
Needed autoconf too
`yum install gcc-c++ autoconf`
